[project]
name = "sir-nauman-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=6.0.0",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
